meilisearch/.helmignore
meilisearch/Chart.yaml
meilisearch/README.md
meilisearch/templates/NOTES.txt
meilisearch/templates/_helpers.tpl
meilisearch/templates/configmap.yaml
meilisearch/templates/ingress.yaml
meilisearch/templates/pvc.yaml
meilisearch/templates/service.yaml
meilisearch/templates/statefulset.yaml
meilisearch/values.yaml

Add meilisearch chart

---

README.md
charts/meilisearch/Chart.yaml
charts/meilisearch/README.md

Improve repository and chart documentation

Guides and documentation

---

charts/meilisearch/Chart.yaml
charts/meilisearch/values.yaml

increased the app version to v0.15.0

---

charts/meilisearch/Chart.yaml
charts/meilisearch/templates/NOTES.txt
manifests/meilisearch.yaml

Cleaned up manifests to remove Helm related lines

---

charts/meilisearch/Chart.yaml
charts/meilisearch/templates/NOTES.txt

Feat helm chart updates

---

CONTRIBUTING.md
README.md

Introducing a CONTRIBUTING.md based on MeiliSearch's [contributing template](https://github.com/meilisearch/integration-guides/blob/main/templates/CONTRIBUTING.md) for integrations
Closes #11

Add CONTRIBUTING.md and update README.md

---

charts/meilisearch/Chart.yaml
charts/meilisearch/README.md
charts/meilisearch/templates/pvc.yaml
charts/meilisearch/templates/service.yaml
charts/meilisearch/templates/serviceaccount.yaml
charts/meilisearch/values.yaml

Implement #66 . I add `annotations` to pvc, svc and serviceAccount.
I saw that no one had done this issue and I just had the time😊. I am a beginner in Helm, if there is a mistake, please feel free to point out.
PTAL @eskombro

Add annotations to templates

---

charts/meilisearch/Chart.yaml
charts/meilisearch/README.md
charts/meilisearch/values.yaml

Small PR to update the Readme with the missing `image.pullSecret` entry in the Readme table.
Also set the default value for `image.pullSecret` to null

Add missing `image.pullSecret` entry in Readme table

---

charts/meilisearch/Chart.yaml
charts/meilisearch/README.md
charts/meilisearch/templates/ingress.yaml

Fix ingress by adding variable for service port

---

charts/meilisearch/Chart.yaml
charts/meilisearch/README.md
charts/meilisearch/templates/serviceaccount.yaml
charts/meilisearch/templates/statefulset.yaml
charts/meilisearch/values.yaml

And hide creation of service account behind a boolean (defaults to true to maintain compatibility)
Fixes #107 

Allow specification of custom service account name

---

README.md
charts/meilisearch/Chart.yaml
charts/meilisearch/values.yaml
manifests/meilisearch.yaml

This PR gathers the changes related to the next Meilisearch release (v0.27.0) so that this package is ready when the official release is out.

Changes related to the next Meilisearch release (v0.27.1)

---

charts/meilisearch/Chart.yaml
charts/meilisearch/values.yaml

Following this [issue](https://github.com/meilisearch/meilisearch/issues/2503) and #24 the mount path should be update to allow persistence

Change the mount path with new meili_data path

---

charts/meilisearch/Chart.yaml

Not having reviewed correctly the versioning I must downgrade the version of the package

Reversing a bad version number update

---

index.yaml

Remove v0.20.0 from helm repo

---

README.md
charts/meilisearch/Chart.yaml
charts/meilisearch/values.yaml
manifests/meilisearch.yaml

Update to meilisearch 0.28.1

---

charts/meilisearch/Chart.yaml
charts/meilisearch/templates/ingress.yaml

delete extra curly brace in ingress template #142
- delete extra curly brace in ingress template

delete extra curly brace

---

charts/meilisearch/Chart.yaml
charts/meilisearch/README.md
charts/meilisearch/templates/statefulset.yaml
charts/meilisearch/values.yaml

...
- Adds support for custom sidecar containers.

Add support for extra containers (sidecars)

---

charts/meilisearch/Chart.yaml
charts/meilisearch/README.md
charts/meilisearch/templates/pvc.yaml
charts/meilisearch/templates/statefulset.yaml
charts/meilisearch/values.yaml

Add posibility to use an existing persistence claim

---

charts/meilisearch/Chart.yaml

none
- The current url leads to a not found error

Fix chart homepage url

---

artifacthub-repo.yml

none
- Add Artifact Hub repository metadata file to get the `Verified Publisher` badge at https://artifacthub.io/packages/helm/meilisearch-kubernetes/meilisearch

Add Artifact Hub repository metadata file

---

charts/meilisearch/Chart.yaml

Remove robot@meilisearch from the maintainers list who is making failing the `ct lint --config ct.yaml`
[See](https://github.com/helm/chart-testing/issues/192)

Update maitainers list

---

charts/meilisearch/Chart.yaml
charts/meilisearch/README.md
charts/meilisearch/README.md.gotmpl
manifests/meilisearch.yaml

Related to: meilisearch/integration-guides#257

Fix link for new documentation website

---

.github/workflows/update-chart-manifest.yaml

Fix deprecation file around environment files

---

.github/workflows/update-chart-manifest.yaml

Fix error when trying to load from env

---

.github/workflows/update-chart-manifest.yaml

Fix manifest commit on sync

---

.github/workflows/update-chart-manifest.yaml

Use a new approach to commit the changes

---

.github/workflows/update-chart-manifest.yaml

Fix update-chart-manifest after updating github actions templates

---

charts/meilisearch/Chart.yaml
charts/meilisearch/templates/statefulset.yaml
charts/meilisearch/values.yaml
manifests/meilisearch.yaml

Fixes #234
- Provide an option for setting the `priorityClassName` on the pod

Priority class name

---

charts/meilisearch/Chart.yaml
charts/meilisearch/templates/serviceMonitor.yaml
manifests/meilisearch.yaml

Fix indentation

---

charts/meilisearch/Chart.yaml
charts/meilisearch/README.md
charts/meilisearch/templates/statefulset.yaml
charts/meilisearch/values.yaml
manifests/meilisearch.yaml

[Allow full customisation of probes #233](https://github.com/meilisearch/meilisearch-kubernetes/issues/233)
- ...

Add timeoutSeconds to probes in values.yaml and statefulset.yaml
