meilisearch/meilisearch-kubernetes

charts/meilisearch/Chart.yaml, charts/meilisearch/templates/servicaccount.yaml, charts/meilisearch/templates/serviceaccount.yaml, charts/meilisearch/templates/statefulset.yaml
Add a ServiceAccount to the Application.
It allows us to identify meilisearch by it's service account token. Otherwise it will be assigned the default service account. This identity is also used by service meshes and vault for example. It is generally considered best practice to add a service account to all deployed services.
=> feat(meilisearch-kubernetes) Add ServiceAccount'

README.md, charts/meilisearch/Chart.yaml, charts/meilisearch/values.yaml, manifests/meilisearch.yaml
Manifests are generated by Helm. To generate manifests, run `helm template meilisearch charts/meilisearch > manifests/meilisearch.yaml` at the root folder.
Added a `getting started` section in the root README.md to deploy MeiliSearch using either manifests or Helm chart.
=> Add manifests

manifests/meilisearch.yaml
After the MeiliSearch bump done in https://github.com/meilisearch/meilisearch-kubernetes/pull/17, version must be bumped in cmanifests too!
=> Bump meilisearch on manifests to v0.15.0

charts/meilisearch/Chart.yaml, charts/meilisearch/templates/statefulset.yaml
Like discussed in #27 the readiness and liveness Probe are not working in production in version 0.17.0, because the frontend is disabled.
By calling the health endpoint, which gives us a `204 No Content` this will work
@eskombro , be my guest ;)
=> fix(statefulset): Use healt endpoint for readiness and liveness Probe

.github/workflows/lint-test.yaml
Runs the whole test set every time the CI is triggered, even if there is no change to the Charts. These tasks take less than 3 minutes and let us keep maintaining a safer repo.
=> Delete condition on Helm chart test in CI

manifests/meilisearch.yaml
Fix: Double quote missing on image name
=> FIx: syntax error, double quote missing

ct.yaml
After #51 and changing `master` to `main`, tests are failing. This PR sets the target branch of the `chart-testing-action` to `main` in the `ct.yaml` file
=> Set target-branch to main on chart-testing-action

charts/meilisearch/Chart.yaml, charts/meilisearch/values.yaml
By default, the values of `InitialDelaySeconds` for `readinessProbe` and `livenessProbe` were set to 0. `periodSeconds` was set to 10.
1. This means that the health checks are done as soon as the container starts running. If adding this health check is best practice, it is also good to let some time for the application to start running properly before doing the health check, since a bad response can be read by kubernetess cluster as a failure and it will restart the container.
2. A period of 10 seconds between every health check seems too short for most use-cases. A check every minute seems more appropriate as a default.
These values are of course modifiable on the `values.yaml` file, but having more appropriate values seem better for most use-cases and for users who are not tuning these …
=> Increase default health check delay values: InitialDelaySeconds for readinessProbe and livenessProbe

.github/workflows/release-chart.yaml
This workflow makes use of the [helm/chart-releaser-action](https://github.com/helm/chart-releaser-action) which will automatically create a git tag whenever the the chart `version` changes.  
This will cause a release to be deployed under your [releases](https://github.com/meilisearch/meilisearch-kubernetes/releases) with a referenced `tgz` of the chart ([example](https://github.com/carlreid/meilisearch-kubernetes/releases/tag/meilisearch-0.1.12)). After that, the action will create/update and index.yaml on the `gh-pages` branch ([example](https://github.com/carlreid/meilisearch-kubernetes/tree/gh-pages)) and allow people to use `helm repo add meilisearch https://meilisearch.github.io/meilisearch-kubernetes`
**Note:**
You'll want to create a `gh-pages` branch first before merging this. …
=> Add workflow to release chart and expose via GitHub Pages

README.md, charts/meilisearch/Chart.yaml, charts/meilisearch/templates/statefulset.yaml, charts/meilisearch/values.yaml
We need a way to annotate our pods for integration with other services, so this just adds support for that. Since I was updating these values, I thought I would also map some of those static values from the issue #53.
Resolves: #53
=> Add podAnnotations and expose some static values in values.yaml

.github/workflows/sync-chart-manifest.yaml
This simply executes the `helm template` command and then performs a diff with git to see if there were any changes. If there are changes, then it will create a commit with those changes with the message `[CI] Syncing Helm manifest`.
I did initially have this run on a PR trigger, but it's very annoying if you have made changes to the chart since then you'd need to pull those changes down. Then if you were to follow up with more changes to the chart, it would result in another automated commit. Probably would add quite some noise to the commit history of `[CI] Syncing Helm manifest` 😄 
> The only "problem" I have found with this approach, is that a lot of tags are added to the manifests that are completely unnecessary and pollute them  
In response to this, I assume this is in relation to …
=> Update manifest on push to main

.github/workflows/tests.yaml, charts/meilisearch/Chart.yaml, charts/meilisearch/README.md, charts/meilisearch/templates/_helpers.tpl, charts/meilisearch/templates/master-key-secret.yaml, charts/meilisearch/templates/statefulset.yaml, charts/meilisearch/values.yaml
With these changes, if someone were to set `MEILI_ENV` to `production` and not set `MEILI_MASTER_KEY`, then a cryptographically secure random secret (using `randAlphaNum`) will be created automatically and then loaded as an environment variable.
If you set `MEILI_MASTER_KEY` in the values.yaml, then that is used instead, so no secret is generated/used.
If the env is `development` then no secret is created at all. You could still set `MEILI_MASTER_KEY` in the values.yaml, as those just get loaded in no matter what.
Resolves #19 and maybe #38
=> Generate secret for master key if the env is set to production

.github/workflows/chart-manifest.yaml, .github/workflows/check-chart-manifest.yaml, .github/workflows/update-chart-manifest.yaml
Attempting to tackle the manifest generation a little differently than before due to [this](https://github.com/meilisearch/meilisearch-kubernetes/pull/61#issuecomment-806152097).
To get what I think is the best middle ground, I've now made it so there's simply a check to see if the manifest is out of date, then fail if it is. When investigating, you will see the following message:
> ❌ Manifest update required. Comment on your PR with '@meilisearch sync-manifest' to update the manifest
As it says, comment on the PR with `@meilisearch sync-manifest` will then perform the job of updating the manifest and then adding a new commit to the pending PR. That way, we don't need to commit directly to `main` (due to branch protection) and then don't automatically commit to the working changes on PR …
=> Check for out of sync manifest and add support for generating it automatically via a comment

charts/meilisearch/Chart.yaml, charts/meilisearch/templates/configmap.yaml, charts/meilisearch/templates/ingress.yaml, charts/meilisearch/templates/master-key-secret.yaml, charts/meilisearch/templates/pvc.yaml, charts/meilisearch/templates/service.yaml, charts/meilisearch/templates/serviceaccount.yaml, charts/meilisearch/templates/statefulset.yaml, charts/meilisearch/values.yaml
Added a `customLabel` attribute to `values.yaml` so that the user can costumize labels. This attribute is replicated on all templates `metadata.labels`.
=> Add custom labels

charts/meilisearch/Chart.yaml, charts/meilisearch/templates/service.yaml
=> Support for specifying Nodeport in service

charts/meilisearch/Chart.yaml, charts/meilisearch/README.md, charts/meilisearch/templates/_helpers.tpl, charts/meilisearch/templates/statefulset.yaml, charts/meilisearch/values.yaml
Adds the functionality to specify an existing secret that has the MEILI_MASTER_KEY defined.
Thank you so much for contributing to MeiliSearch!
=> Allow an existing secret to be used

charts/meilisearch/Chart.yaml, charts/meilisearch/templates/ingress.yaml
Add the ingressClassName field  if the k8s version higher then 1.19-0.
See: https://kubernetes.github.io/ingress-nginx/#what-is-an-ingressclass-and-why-is-it-important-for-users-of-ingress-nginx-controller-now
Fixes #116
=> Fix ingress does not contain a valid IngressClass

charts/meilisearch/Chart.yaml, charts/meilisearch/templates/ingress.yaml, charts/meilisearch/values.yaml
Hello :)
I test the ingress recently fixed (thank you for that) but I can't use it with traefik because of the ingressClassName set as default to `nginx`.
I edited the chart to allow to dynamically change this value. :)
I set nginx as the default value but in my opinion not className should be the default value.
Anyway this improvement works for me.
Have a nice day!
=> feat: allow other ingress class than Nginx

charts/meilisearch/Chart.yaml, charts/meilisearch/README.md, charts/meilisearch/templates/statefulset.yaml, charts/meilisearch/values.yaml
Fixes #149
- Add `volumes` values for additional volumes on pods
- Add `volumeMounts` values to mount them on pods
- Add `envFrom` values to specify potential secrets to inject in pods.
Feedback welcome!
I bumped the version to 0.1.43, let me know if that's not how you handle versioning.
=> Add possibility to mount volumes and specify envFrom to inject variables

charts/meilisearch/Chart.yaml, charts/meilisearch/templates/statefulset.yaml, charts/meilisearch/values.yaml, manifests/meilisearch.yaml
Fixes long startup delay
Instead of waiting initialDelaySeconds=60 (by default) for the pod to be ready, add a startupProbe which cheks every periodSeconds=1 during failureThreshold=60 iterations.
=> replace initialDelaySeconds by a startupProbe

charts/meilisearch/Chart.yaml, charts/meilisearch/README.md
The README.md is missing documentation of the `ingress.className` value.  If you mistakenly use an annotation like `kubernetes.io/ingress.class: nginx` you will get an error and scratch your head about how to address it.
=> Document missing ingress.className value in README.md

README.md
I think in this particular repository, our default message:
> This package guarantees compatibility with [version v1.x of Meilisearch](https://github.com/meilisearch/meilisearch/releases/latest), but some features may not be present. Please check the [issues](https://github.com/meilisearch/meilisearch-kubernetes/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+label%3Aenhancement) for more info.
It does not make much sense since the chart is permanently attached to a particular version of Meilisearch.
=> Rollback compatibility version on README.md

charts/meilisearch/Chart.yaml, charts/meilisearch/README.md, charts/meilisearch/templates/statefulset.yaml, charts/meilisearch/values.yaml, manifests/meilisearch.yaml
Fixes #174 
- This PR adds a new key named `podLabels` in `values.yaml`. Analogous to `podAnnotations` this key defines an object of key-value pairs.
=> feat: add Pod specific labels

charts/meilisearch/Chart.yaml, charts/meilisearch/README.md, charts/meilisearch/templates/statefulset.yaml, charts/meilisearch/values.yaml, manifests/meilisearch.yaml
- https://github.com/meilisearch/meilisearch/issues/2051  (it's just a relevant issue raised on the meilisearch image level)
This PR was created in the continuation to our discussion here: https://github.com/meilisearch/meilisearch-kubernetes/pull/176#discussion_r1222197366
That PR changes the default behaviour of the chart so it runs meilisearch under a non-root user, following the principal of least permissions and improve the security posture:
- Enable `securityContext.readOnlyRootFilesystem: true` by default and mount required writable points:
- `/tmp` as `emptyDir: {}` [1]
- `/meili_data` as `emptyDir: {}` by default, or as a PVC if `persistence.enabled: true`
- Default values `fsGroup: 1000` and `fsGroupChangePolicy: OnRootMismatch` allow to keep backward compatibility with existing …
=> Run meilisearch as non-root user with readOnlyRootFilesystem

charts/meilisearch/Chart.yaml, charts/meilisearch/templates/statefulset.yaml, manifests/meilisearch.yaml
- Re-enable the possibility to customize the `spec.replicas` value of the StatefulSet, a requirement we have for our internal High Availability tests.
- Keep a default value of 1 replica to match the most common uses.
=> feat: reintroduce the possibility to specify a replicaCount in values.yaml

charts/meilisearch/Chart.yaml, charts/meilisearch/templates/master-key-secret.yaml, charts/meilisearch/templates/serviceMonitor.yaml, ct.yaml, manifests/meilisearch.yaml
- Fix hard coded meilisearch-master-key ref in serviceMonitor. The serviceMonitor was broken when the helm deployment name was changed from the default `meilisearch`. This also uses the existing template for all secretMasterKeyName usages which ensures consistency.
N.B. Please also consider fixing the language used in the application and this chart. "Master" is a dated and divisive term.
=> Fix hard coded meilisearch-master-key ref in serviceMonitor

charts/meilisearch/Chart.yaml, charts/meilisearch/templates/statefulset.yaml, charts/meilisearch/values.yaml, manifests/meilisearch.yaml
Fixes #226
- Enables support for `initContainers` consistent with enablement for `containers` and `volumes` etc
I was able to create an `initContainer` pattern that pulled a `.dump` file from S3 and mounted it into the Meili pod using the following values:
```
initContainers:
- name: aws-copy
image: amazon/aws-cli
envFrom:
- configMapRef:
name: env-with-s3-creds
command:
- "/bin/sh"
- "-c"
- aws s3 cp "s3://$S3_BUCKET/meilisearch_dumps" /meili_data/dumps --recursive
volumeMounts:
- name: meili-dumps
mountPath: /meili_data/dumps
volumes:
- name: meili-dumps
emptyDir: {}
volumeMounts:
- name: meili-dumps
mountPath: /meili_data/dumps
environment:
MEILI_IMPORT_DUMP: /meili_data/dumps/myClonedDumpFile.dump
MEILI_ENV: development
MEILI_MASTER_KEY: someReallyCoolKeyAlsoWookiesRule …
```
=> Add initContainer support

charts/meilisearch/Chart.yaml, manifests/meilisearch.yaml
Just in case someone removes it :)
The new URL is under our [integration-guides repo](https://github.com/meilisearch/integration-guides/)
=> Replace Chart.yml icon by a well known image URL

charts/meilisearch/Chart.yaml, charts/meilisearch/values.yaml, manifests/meilisearch.yaml
N/A
- Sets the default storageClass value to align with documentation beside it.  Requires one less variable be defined for a quick setup.
- [X ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
=> change default to unset storageclass

charts/meilisearch/Chart.yaml, charts/meilisearch/templates/serviceMonitor.yaml, charts/meilisearch/values.yaml, manifests/meilisearch.yaml
In the default values the serviceMonitor.Namespace is available but this is not taking into account
- ...
=> Support dynamic serviceMonitor Namespace

charts/meilisearch/Chart.yaml, manifests/meilisearch.yaml
Fixes https://github.com/meilisearch/meilisearch-kubernetes/issues/254
I've inadvertently released the new engine v1.14.0 as v0.12.1 (patch) when it should be a minor version v0.13.0, so I'm doing it now.
This release introduces no change.
=> Release v0.13.0
